### ISSUE TITLE
igl.random_points_on_mesh,error : too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by fank996** [sgsellan/fracture-modes#10]

**Comment by sgsellan** [comment]
Could you please share a minimal working example, with version details on a fresh environment, to replicate this error?

Thanks!

**Comment by fank996** [comment]
Thank you, I have already resolved this issue

> 您能否分享一个最小的工作示例，其中包含新环境中的版本详细信息，以复制此错误？
> 
> 谢谢！

Thank you, I have already resolved this issue

**Comment by fank996** [comment]
> 您能否分享一个最小的工作示例，其中包含新环境中的版本详细信息，以复制此错误？
> 
> 谢谢！

This issue is due to the fact that igl. random_points.on_mesh has three outputs, while your code only has two outputs, so it cannot correspond. I believe it is a version correspondence issue
