### ISSUE TITLE
How can I control the number of fragments generated?

### ISSUE THREAD

**Issue by supgy** [sgsellan/fracture-modes#12]
Hi，its really a nice work！ I have a question, How can I control the number of fractures an object generated? For example, an object breaks into two or three parts, I want generate 50 options，what should I do？

**Comment by sgsellan** [comment]
Thank you! Unfortunately, I cannot think of a way to directly use this code to do what you want efficiently. All I can propose is that you use rejection sampling: use few modes, simulate many, many impacts, and keep only the ones with 2/3 pieces. Repeat (could take a while) until you only have two pieces. That, or simulate an impact and merge some pieces (maybe in order of size) until you have two or three.

**Comment by supgy** [comment]
Thanks for your reply, this is also a good idea， I will have a try~
