### ISSUE TITLE
import error on ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by nnkgw** [sgsellan/fracture-modes#8]
When I execute "python scripts/example.py", this import error is displayed.

ImportError: /home/nobuo/anaconda3/envs/fracture-modes/lib/python3.9/site-packages/igl/../../../libstdc++.so.6:
version `GLIBCXX_3.4.30' not found (required by
/home/nobuo/anaconda3/envs/fracture-modes/lib/python3.9/site-packages/scipy/fft/_pocketfft/[pypocketfft.cpython-39-x86_64-linux-gnu.so](http://pypocketfft.cpython-39-x86_64-linux-gnu.so/))

I attached the full error output.
[import_err.txt](https://github.com/sgsellan/fracture-modes/files/10323315/import_err.txt)

I am using anaconda (2022.10) on Ubuntu 20.04.5 LTS.

**Comment by nnkgw** [comment]
I use older version of scipy to fix import error.

`conda install scipy==1.9.1`

Finally, I can execute your code on  miniconda(py39_22.11.1-1) on ubuntu 20.04.05 LTS!
Thanks.

![image](https://user-images.githubusercontent.com/1611293/210128596-c13d9b88-c054-4960-8397-8fffc6524d37.png)

**Comment by sgsellan** [comment]
Awesome!
