### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ahaemhumright** [sgsellan/fracture-modes#9]
Great work!
However, some error occurred when I execute "python scripts/example.py"

from pyvista._vtk import VTK9
ImportError: cannot import name 'VTK9' from 'pyvista._vtk'

Do you have any suggestions on the error?

**Comment by sgsellan** [comment]
Thanks!

I have never seen this error before. Can you please post the *full* error message? Specifically I am trying to find where the line `from pyvista._vtk import VTK9` is being called.

**Comment by sgsellan** [comment]
Actually, after digging a little, this seems to be a line called by `tetgen`, one of our dependencies: https://github.com/pyvista/tetgen/blob/master/tetgen/pytetgen.py

Could you confirm that the error occurs if you don't use our code at all, and instead just try to run tetgen? If so, please submit an issue to them

**Comment by ahaemhumright** [comment]
Thanks a lot! It is a error when calling "import tetgen". I will submit the issue to tetgen.
